module.exports = {
  branches: ['main'],
  plugins: [
    ['@semantic-release/commit-analyzer', { preset: 'conventionalcommits' }],
    ['@semantic-release/npm', { pkgRoot: 'packages/springstack', npmPublish: false }],
    [
      '@semantic-release/exec',
      {
        generateNotesCmd: "node -e \"console.log('Release notes are currently generated by semantic-release without commit dates.');\"",
        publishCmd: 'cd packages/springstack && NODE_AUTH_TOKEN= NPM_CONFIG_PROVENANCE=true npm publish --access public --provenance'
      }
    ],
    '@semantic-release/github'
  ]
};
